### ISSUE TITLE
Error when setting up Git

### ISSUE THREAD

**Issue by jsogge** [ComS342-ISU/course-info#1]
When attempting to follow the guide to set up Git, I receive a "fatal: remote origin already exists" error when attempting the "$ git remote add origin git@github.com:ComS342-ISU/hw-answers-<NetID>.git" step.

Additionally the result from the prior "$ git remote -v" command results in a response that includes an "origin", unlike the example.

See attached image for both.

![git_error](https://f.cloud.github.com/assets/6422545/1950787/5140b38c-8159-11e3-9efd-6fdd3c6f00a0.png)

Attempting to remove the "origin" per StackOverflow suggestions using the "$ git remote rm origin" command doesn't work, instead resulting in the error "error: Could not remove config section 'remote.origin'".

This is on a fresh Win 7 Pro install in a virtual environment, post Git for Windows install.

**Comment by jdavis** [comment]
Hey Jessica.

A few people have ran into this issue as well. It appears to happen to some and not others.

Instead of adding the origin again, try this command:

``` bash
$ git remote set-url origin git@github.com:ComS342-ISU/hw-answers-jsogge.git
```

Let me know if it works.

**Comment by jsogge** [comment]
That appears to have worked.
